# Configuration for welcome - https://github.com/behaviorbot/welcome
newIssueWelcomeComment: |
  ğŸ’– Thanks for opening this issue. ğŸ’–

  A Codinasion team member should be by to give feedback soon.
firstPRMergeComment: |
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰
